export const personalInfo = {
  name: 'Blessy Nookathati',
  role: 'Full-Stack Developer & Software Engineer',
  tagline: 'Crafting responsive, high-performance web applications with modern frontend architectures and scalable backend services.',
  location: 'Available Worldwide / Remote',
  email: 'nookathatiblessy@gmail.com',
  github: 'https://github.com/blessynookathati',
  linkedin: 'https://linkedin.com/in/blessynookathati',
  codechef: 'https://www.codechef.com/users/blessy_roy_08',
  bio: 'Computer Science undergraduate passionate about building impactful software solutions. Experienced in developing full-stack web applications using React, Node.js, and modern cloud technologies. Solved 1300+ problems across competitive programming platforms with a deep focus on algorithmic efficiency and user-centric frontend experiences.',
};

export const skillsData = [
  {
    name: 'React.js',
    category: 'Frontend',
    level: 'Advanced',
    color: '#61DAFB',
    description: 'Hooks, Context API, state management, SPA architecture, performance optimization',
  },
  {
    name: 'JavaScript (ES6+)',
    category: 'Languages',
    level: 'Advanced',
    color: '#F7DF1E',
    description: 'Async/Await, DOM manipulation, functional programming, Event loop',
  },
  {
    name: 'Tailwind CSS',
    category: 'Frontend',
    level: 'Advanced',
    color: '#38BDF8',
    description: 'Utility-first styling, custom theme configurations, responsive design, dark mode',
  },
  {
    name: 'Framer Motion',
    category: 'Frontend',
    level: 'Intermediate',
    color: '#EC4899',
    description: 'Declarative physics-based animations, layout transitions, scroll-triggered animations',
  },
  {
    name: 'Node.js & Express',
    category: 'Backend',
    level: 'Proficient',
    color: '#22C55E',
    description: 'RESTful API development, JWT authentication, middleware pipelines, WebSockets',
  },
  {
    name: 'Python',
    category: 'Languages',
    level: 'Advanced',
    color: '#3B82F6',
    description: 'Data structures, algorithm implementations, scripting, automation, backend integration',
  },
  {
    name: 'Git & GitHub',
    category: 'Tools',
    level: 'Proficient',
    color: '#F05032',
    description: 'Version control workflows, branching strategies, collaborative development, CI/CD',
  },
  {
    name: 'Responsive & Accessible Design',
    category: 'Frontend',
    level: 'Advanced',
    color: '#A855F7',
    description: 'Mobile-first layouts, WCAG accessibility, fluid typography, cross-browser compatibility',
  },
];

export const projectsData = [
  {
    id: 'whiteboard',
    title: 'Real-Time Collaborative Whiteboard',
    description: 'Interactive multi-user digital canvas enabling simultaneous sketching, sticky notes, and real-time state synchronization via WebSockets.',
    tags: ['React', 'HTML5 Canvas', 'Node.js', 'Socket.io', 'Tailwind CSS'],
    liveUrl: 'https://whiteboard-demo.example.com',
    githubUrl: 'https://github.com/blessynookathati/collaborative-whiteboard',
    badge: 'Featured',
  },
  {
    id: 'ai-resume',
    title: 'AI Resume & Portfolio Builder',
    description: 'Dynamic resume builder with instant real-time live preview, ATS scoring analyzer, and seamless PDF export capabilities.',
    tags: ['React', 'Tailwind CSS', 'Framer Motion', 'Local Storage', 'Vite'],
    liveUrl: 'https://ai-resume.example.com',
    githubUrl: 'https://github.com/blessynookathati/ai-resume-builder',
    badge: 'Popular',
  },
  {
    id: 'payment-gateway',
    title: 'Payment Gateway Integration Hub',
    description: 'Enterprise payment orchestration layer handling asynchronous webhook notifications, refund processing, and idempotency guarantees.',
    tags: ['Python', 'REST APIs', 'Webhooks', 'Docker', 'PostgreSQL'],
    liveUrl: 'https://payments.example.com',
    githubUrl: 'https://github.com/blessynookathati/payment-gateway-hub',
    badge: 'Backend',
  },
  {
    id: 'product-filtering',
    title: 'E-Commerce Product Filtering Engine',
    description: 'Ultra-fast multi-faceted product search & filtering interface featuring debounced query searches, tag filters, and url sync.',
    tags: ['React', 'JavaScript ES6+', 'Tailwind CSS', 'Context API'],
    liveUrl: 'https://product-filter.example.com',
    githubUrl: 'https://github.com/blessynookathati/ecommerce-filter-app',
    badge: 'Frontend',
  },
  {
    id: 'job-board',
    title: 'Modern Tech Career Portal',
    description: 'Comprehensive developer job board featuring interactive bookmarks, applicant tracking, salary filters, and persistent application drafts.',
    tags: ['React', 'React Hook Form', 'Tailwind CSS', 'Framer Motion'],
    liveUrl: 'https://tech-careers.example.com',
    githubUrl: 'https://github.com/blessynookathati/tech-career-portal',
    badge: 'Full-Stack',
  },
  {
    id: 'algorithm-visualizer',
    title: 'Algorithm & Data Structure Visualizer',
    description: 'Interactive visualization platform for sorting, graph traversal, and tree searching algorithms with step-by-step playback.',
    tags: ['React', 'Algorithms', 'Framer Motion', 'Canvas'],
    liveUrl: 'https://algo-visualizer.example.com',
    githubUrl: 'https://github.com/blessynookathati/algorithm-visualizer',
    badge: 'Interactive',
  },
];
